# Generated by Django 2.0 on 2018-05-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('skype_telegram', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
            ],
        ),
    ]
