# Generated by Django 2.0 on 2018-05-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_auto_20180524_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=models.CharField(default=False, max_length=400),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
